TIMBERS_ISLAND_BALLOON = "Timber's Island Balloon"
DINO_DOMAIN_BALLOON = "Dino Domain Balloon"
SNOWFLAKE_MOUNTAIN_BALLOON = "Snowflake Mountain Balloon"
SHERBET_ISLAND_BALLOON = "Sherbet Island Balloon"
DRAGON_FOREST_BALLOON = "Dragon Forest Balloon"
FUTURE_FUN_LAND_BALLOON = "Future Fun Land Balloon"

FIRE_MOUNTAIN_KEY = "Fire Mountain Key"
ICICLE_PYRAMID_KEY = "Icicle Pyramid Key"
DARKWATER_BEACH_KEY = "Darkwater Beach Key"
SMOKEY_CASTLE_KEY = "Smokey Castle Key"

WIZPIG_AMULET_PIECE = "Wizpig Amulet Piece"
TT_AMULET_PIECE = "T.T. Amulet Piece"

DINO_DOMAIN_UNLOCK = "Dino Domain Unlock"
SNOWFLAKE_MOUNTAIN_UNLOCK = "Snowflake Mountain Unlock"
SHERBET_ISLAND_UNLOCK = "Sherbet Island Unlock"
DRAGON_FOREST_UNLOCK = "Dragon Forest Unlock"

ANCIENT_LAKE_1_UNLOCK = "Ancient Lake 1 Unlock"
ANCIENT_LAKE_2_UNLOCK = "Ancient Lake 2 Unlock"
FOSSIL_CANYON_1_UNLOCK = "Fossil Canyon 1 Unlock"
FOSSIL_CANYON_2_UNLOCK = "Fossil Canyon 2 Unlock"
JUNGLE_FALLS_1_UNLOCK = "Jungle Falls 1 Unlock"
JUNGLE_FALLS_2_UNLOCK = "Jungle Falls 2 Unlock"
HOT_TOP_VOLCANO_1_UNLOCK = "Hot Top Volcano 1 Unlock"
HOT_TOP_VOLCANO_2_UNLOCK = "Hot Top Volcano 2 Unlock"
EVERFROST_PEAK_1_UNLOCK = "Everfrost Peak 1 Unlock"
EVERFROST_PEAK_2_UNLOCK = "Everfrost Peak 2 Unlock"
WALRUS_COVE_1_UNLOCK = "Walrus Cove 1 Unlock"
WALRUS_COVE_2_UNLOCK = "Walrus Cove 2 Unlock"
SNOWBALL_VALLEY_1_UNLOCK = "Snowball Valley 1 Unlock"
SNOWBALL_VALLEY_2_UNLOCK = "Snowball Valley 2 Unlock"
FROSTY_VILLAGE_1_UNLOCK = "Frosty Village 1 Unlock"
FROSTY_VILLAGE_2_UNLOCK = "Frosty Village 2 Unlock"
WHALE_BAY_1_UNLOCK = "Whale Bay 1 Unlock"
WHALE_BAY_2_UNLOCK = "Whale Bay 2 Unlock"
CRESCENT_ISLAND_1_UNLOCK = "Crescent Island 1 Unlock"
CRESCENT_ISLAND_2_UNLOCK = "Crescent Island 2 Unlock"
PIRATE_LAGOON_1_UNLOCK = "Pirate Lagoon 1 Unlock"
PIRATE_LAGOON_2_UNLOCK = "Pirate Lagoon 2 Unlock"
TREASURE_CAVES_1_UNLOCK = "Treasure Caves 1 Unlock"
TREASURE_CAVES_2_UNLOCK = "Treasure Caves 2 Unlock"
WINDMILL_PLAINS_1_UNLOCK = "Windmill Plains 1 Unlock"
WINDMILL_PLAINS_2_UNLOCK = "Windmill Plains 2 Unlock"
GREENWOOD_VILLAGE_1_UNLOCK = "Greenwood Village 1 Unlock"
GREENWOOD_VILLAGE_2_UNLOCK = "Greenwood Village 2 Unlock"
BOULDER_CANYON_1_UNLOCK = "Boulder Canyon 1 Unlock"
BOULDER_CANYON_2_UNLOCK = "Boulder Canyon 2 Unlock"
HAUNTED_WOODS_1_UNLOCK = "Haunted Woods 1 Unlock"
HAUNTED_WOODS_2_UNLOCK = "Haunted Woods 2 Unlock"
SPACEDUST_ALLEY_1_UNLOCK = "Spacedust Alley 1 Unlock"
SPACEDUST_ALLEY_2_UNLOCK = "Spacedust Alley 2 Unlock"
DARKMOON_CAVERNS_1_UNLOCK = "Darkmoon Caverns 1 Unlock"
DARKMOON_CAVERNS_2_UNLOCK = "Darkmoon Caverns 2 Unlock"
SPACEPORT_ALPHA_1_UNLOCK = "Spaceport Alpha 1 Unlock"
SPACEPORT_ALPHA_2_UNLOCK = "Spaceport Alpha 2 Unlock"
STAR_CITY_1_UNLOCK = "Star City 1 Unlock"
STAR_CITY_2_UNLOCK = "Star City 2 Unlock"

VICTORY = "Victory"

ALL_BALLOON_ITEMS = [
    TIMBERS_ISLAND_BALLOON,
    DINO_DOMAIN_BALLOON,
    SNOWFLAKE_MOUNTAIN_BALLOON,
    SHERBET_ISLAND_BALLOON,
    DRAGON_FOREST_BALLOON,
    FUTURE_FUN_LAND_BALLOON
]

DOOR_UNLOCK_ITEMS = [
    ANCIENT_LAKE_1_UNLOCK,
    ANCIENT_LAKE_2_UNLOCK,
    FOSSIL_CANYON_1_UNLOCK,
    FOSSIL_CANYON_2_UNLOCK,
    JUNGLE_FALLS_1_UNLOCK,
    JUNGLE_FALLS_2_UNLOCK,
    HOT_TOP_VOLCANO_1_UNLOCK,
    HOT_TOP_VOLCANO_2_UNLOCK,
    EVERFROST_PEAK_1_UNLOCK,
    EVERFROST_PEAK_2_UNLOCK,
    WALRUS_COVE_1_UNLOCK,
    WALRUS_COVE_2_UNLOCK,
    SNOWBALL_VALLEY_1_UNLOCK,
    SNOWBALL_VALLEY_2_UNLOCK,
    FROSTY_VILLAGE_1_UNLOCK,
    FROSTY_VILLAGE_2_UNLOCK,
    WHALE_BAY_1_UNLOCK,
    WHALE_BAY_2_UNLOCK,
    CRESCENT_ISLAND_1_UNLOCK,
    CRESCENT_ISLAND_2_UNLOCK,
    PIRATE_LAGOON_1_UNLOCK,
    PIRATE_LAGOON_2_UNLOCK,
    TREASURE_CAVES_1_UNLOCK,
    TREASURE_CAVES_2_UNLOCK,
    WINDMILL_PLAINS_1_UNLOCK,
    WINDMILL_PLAINS_2_UNLOCK,
    GREENWOOD_VILLAGE_1_UNLOCK,
    GREENWOOD_VILLAGE_2_UNLOCK,
    BOULDER_CANYON_1_UNLOCK,
    BOULDER_CANYON_2_UNLOCK,
    HAUNTED_WOODS_1_UNLOCK,
    HAUNTED_WOODS_2_UNLOCK,
    SPACEDUST_ALLEY_1_UNLOCK,
    SPACEDUST_ALLEY_2_UNLOCK,
    DARKMOON_CAVERNS_1_UNLOCK,
    DARKMOON_CAVERNS_2_UNLOCK,
    SPACEPORT_ALPHA_1_UNLOCK,
    SPACEPORT_ALPHA_2_UNLOCK,
    STAR_CITY_1_UNLOCK,
    STAR_CITY_2_UNLOCK
]
